### ISSUE TITLE
`truth` must be a factor

### ISSUE THREAD

**Issue by kavinduxo** [tidymodels/yardstick#332] opened 2022-10-21 22:44 UTC
#When trying to create a confusion matrix below error appeared.
Code :
`cm <- conf_mat(test_df.scored, truth = LeagueIndex, class)`

Error:
**Error in `yardstick_table()`:**
**! `truth` must be a factor.**
ℹ This is an internal error that was detected in the yardstick package.
  Please report it at <https://github.com/tidymodels/yardstick/issues> with a reprex and the full backtrace.
Backtrace:
 1. yardstick::conf_mat(test_df.scored, truth = LeagueIndex, class)
 2. yardstick:::conf_mat.data.frame(...)
 3. yardstick:::yardstick_table(truth = truth, estimate = estimate, case_weights = case_weights)
 Error in yardstick_table(truth = truth, estimate = estimate, case_weights = case_weights) :

Thanks/

**Comment by EmilHvitfeldt** [comment] 2022-10-25 23:41
This is a duplicate of https://github.com/tidymodels/yardstick/issues/327.

without seeing more data or code I can't give more advice. If you could show the output of `str(test_df.scored)` that would be helpful. From the error message, it appears that `LeagueIndex` the `truth` is not a factor which it must be in `conf_mat()`.

**Closed** 2023-01-23 18:31 UTC
