### ISSUE TITLE
Calibratrion metrics x Discriminant metrics 

### ISSUE THREAD

**Issue by gustavomodelli** [tidymodels/yardstick#202] opened 2021-02-18 23:10 UTC
### Calibration Metrics in Tidymodels

 I would like to request calibration metrics to yardstick as https://github.com/tidymodels/yardstick/issues/150

I fitted a model using tidymodels and select the best model by 10-fold-cross validation and test the accuracy with roc_auc and confusion matrix. This model was submitted to publication and the reviewers request the calibration metrics. I perform these calibration metrics using the RMS package. I had a disagreement in Elastic Net between discriminant metrics (roc_auc, sensibility, and specificity) and calibration metrics (Brier Score and slope values).

Can anyone help me with this divergence between calibration and discrimination measures? Was the model trained using measures of discrimination (roc_auc) and not calibration justifying the difference? Which measure is most relevant?

**Comment by DavisVaughan** [comment] 2021-02-19 13:47
If you used roc-auc in your cross validation, then there were no calibration measures involved.

We have not yet added any calibration metrics to tidymodels.

I consider this issue a duplicate of #150, so I'm going to close!

**Closed by DavisVaughan** 2021-02-19 13:47 UTC
