### ISSUE TITLE
Hard deprecate `yardstick.event_first` global option 

### ISSUE THREAD

**Issue by DavisVaughan** [tidymodels/yardstick#173] opened 2020-07-09 19:39 UTC
This is a breaking change

This issue is a sign post reminder to hard deprecate the global option that we have soft deprecated in #172 in favor of the explicit `event_level` argument.

**Comment by PhoenixB** [comment] 2020-09-28 14:57
Hi @DavisVaughan,

When I do resampling like in the following code example, the metrics will use the first level of the outcome:
```
resamples <-
  workflow %>%
  fit_resamples(
    training_folds,
    metrics = NULL
  )
```
(This example is actually not reproducible)

Is it possible to change this behaviour with an `event_level` argument somewhere?

Regards,
Pascal

**Comment by DavisVaughan** [comment] 2020-09-28 17:18
For now you have to use `options(yardstick.event_first = FALSE)` and there is a chance that wont even work because of https://github.com/tidymodels/tune/issues/240. We will get tune and probably changed over to use the new system before deprecating

**Comment by PhoenixB** [comment] 2020-09-30 15:45
Hi!

Can you explain this behaviour? With the global option `yardstick.event_first` set to `FALSE` and having `no` as the first factor level, the ROC-AUC is exactly 1 minus the result when `yardstick.event_first` is set to `TRUE` and having `yes` as the first level.

Shouldn't they be exactly the same?

``` r
library(tidyverse)
library(tidymodels)

data("titanic_imputed", package = "DALEX")

options(yardstick.event_first = FALSE)

titanic_data <-
  titanic_imputed %>%
  as_tibble() %>%
  mutate(survived = factor(survived, levels = c("0", "1"), labels = c("no", "yes")))

training_folds <-
  vfold_cv(titanic_data, v = 10, repeats = 2, strata = survived)

model.glm <-
  logistic_reg() %>%
  set_engine("glm")

workflow.glm <-
  workflow() %>%
  add_formula(survived ~ .) %>%
  add_model(model.glm)

fit.glm <-
  workflow.glm %>%
  fit(data = titanic_data)

resamples.glm <-
  workflow.glm %>%
  fit_resamples(
    training_folds,
    metrics = metric_set(accuracy, roc_auc),
    control = control_resamples(
      save_pred = TRUE
      )
    )
#> ! Fold01, Repeat1: internal: The `yardstick.event_first` option has been deprecated as of y...

collect_metrics(resamples.glm)
#> # A tibble: 2 x 5
#>   .metric  .estimator  mean     n std_err
#>   <chr>    <chr>      <dbl> <int>   <dbl>
#> 1 accuracy binary     0.798    20 0.00456
#> 2 roc_auc  binary     0.194    20 0.00524
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
library(tidyverse)
library(tidymodels)

data("titanic_imputed", package = "DALEX")

options(yardstick.event_first = TRUE)

titanic_data <-
  titanic_imputed %>%
  as_tibble() %>%
  mutate(survived = factor(survived, levels = c("1", "0"), labels = c("yes", "no")))

training_folds <-
  vfold_cv(titanic_data, v = 10, repeats = 2, strata = survived)

model.glm <-
  logistic_reg() %>%
  set_engine("glm")

workflow.glm <-
  workflow() %>%
  add_formula(survived ~ .) %>%
  add_model(model.glm)

fit.glm <-
  workflow.glm %>%
  fit(data = titanic_data)

resamples.glm <-
  workflow.glm %>%
  fit_resamples(
    training_folds,
    metrics = metric_set(accuracy, roc_auc),
    control = control_resamples(
      save_pred = TRUE
      )
    )
#> ! Fold01, Repeat1: internal: The `yardstick.event_first` option has been deprecated as of y...

collect_metrics(resamples.glm)
#> # A tibble: 2 x 5
#>   .metric  .estimator  mean     n std_err
#>   <chr>    <chr>      <dbl> <int>   <dbl>
#> 1 accuracy binary     0.797    20 0.00369
#> 2 roc_auc  binary     0.807    20 0.00567
```

<sup>Created on 2020-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment] 2020-09-30 16:08
Please open a new issue if you have questions. I'm happy to discuss, but this issue is specifically about deprecation of the option, not about any behavior. I'm going to hide these comments. Again, I'm happy to discuss in a new issue!

**Comment by jkylearmstrong** [comment] 2021-05-21 06:39
Hi there - is there any replacement for
```{r}
options(yardstick.event_first = FALSE) 
```

I reviewed https://github.com/tidymodels/yardstick/pull/172 and I understand the reasoning behind wanting to be more explict however, if in my analysis I performed:

1. ROC Curve
2. PR Curve
3. Lift Curve
4. Gain Curve
5. Confusion Matrix

I need to edit 5 calls to various yardstick functions - if all 5 go in the same direction I do think it makes sense to specify the event level 1 time versus 5!

**Comment by DavisVaughan** [comment] 2021-05-21 12:48
No, I very strongly believe that making the argument explicit is an overall improvement in terms of reproducibility when weighed against having to potentially specify the argument multiple times. See also https://design.tidyverse.org/args-hidden.html#what-are-some-examples

**Comment by DavisVaughan** [comment] 2022-09-01 18:47
The next stage of deprecation would probably be to continue to give the warning if we see that the option is being used, but then just ignore the global option altogether.

After that we would just remove the warning

**Comment by EmilHvitfeldt** [comment] 2023-02-16 22:32
closed in https://github.com/tidymodels/yardstick/pull/358

**Closed by EmilHvitfeldt** 2023-02-16 22:32 UTC
Labels: Next release, breaking change :skull_and_crossbones:
