### ISSUE TITLE
Add weights argument?

### ISSUE THREAD

**Issue by brshallo** [tidymodels/yardstick#102] opened 2019-04-16 18:46 UTC
As an example, when including `weights` in `lm`, the r squared returned is a weighted value.  Is there a way to mirror this in `yardstick`, does it make sense to add a `weights` argument?

``` r
library(tidyverse)

mod_diamonds_weighted <- lm(carat ~ cut + color, weights = price, data = diamonds)

# lm returns a weighted r squared value
mod_diamonds_weighted %>% 
  broom::glance() %>% 
  select(r.squared)
#> # A tibble: 1 x 1
#>   r.squared
#>       <dbl>
#> 1     0.172

# unweighted r squared value (would adding a `weights` argument make sense?)
diamonds %>% 
  modelr::add_predictions(mod_diamonds_weighted) %>% 
  yardstick::rsq(carat, pred)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 rsq     standard       0.119

# are equal for un-weighted (as expected)
mod_diamonds_unweighted <- lm(carat ~ cut + color, data = diamonds)

mod_diamonds_unweighted %>% 
  broom::glance() %>% 
  select(r.squared)
#> # A tibble: 1 x 1
#>   r.squared
#>       <dbl>
#> 1     0.124

diamonds %>% 
  modelr::add_predictions(mod_diamonds_unweighted) %>% 
  yardstick::rsq(carat, pred)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 rsq     standard       0.124

### P.s. modelr::rsquare does something different from `lm` in the weighted example...
modelr::rsquare(model = mod_diamonds_weighted, data = diamonds)
#> [1] 0.1091624
```

<sup>Created on 2019-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment] 2019-08-13 21:23
Duplicate of #30

**Closed by DavisVaughan** 2019-08-13 21:23 UTC
